using ClubGear.Data;
using ClubGear.Models;
using ClubGear.Services.Abstractions;
using ClubGear.Services.Core;
using Microsoft.Data.Sqlite;
using Microsoft.EntityFrameworkCore;
using Xunit;

namespace ClubGear.ArchitectureTests;

public sealed class MemberFeatureServiceTests
{
    [Fact]
    public async Task CreateAsync_AutoGeneratesMemberNumber_FromConfiguredNumberRange()
    {
        using var connection = new SqliteConnection("Filename=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var db = new ApplicationDbContext(options);
        await db.Database.EnsureCreatedAsync();

        db.SystemConfigEntries.AddRange(
            new SystemConfigEntry { Section = "Members", Name = "MemberNumberPrefix", Value = "MB-", Description = string.Empty, UpdatedAtUtc = DateTime.UtcNow },
            new SystemConfigEntry { Section = "Members", Name = "MemberNumberSuffix", Value = "-A", Description = string.Empty, UpdatedAtUtc = DateTime.UtcNow },
            new SystemConfigEntry { Section = "Members", Name = "MemberNumberNextNumber", Value = "42", Description = string.Empty, UpdatedAtUtc = DateTime.UtcNow },
            new SystemConfigEntry { Section = "Members", Name = "MemberNumberPadding", Value = "5", Description = string.Empty, UpdatedAtUtc = DateTime.UtcNow });
        await db.SaveChangesAsync();

        var service = new MemberFeatureService(db, new NoopAuditLogService());

        await service.CreateAsync(new Member
        {
            FirstName = "Ada",
            LastName = "Lovelace",
            IsActive = true,
            JoinedAt = DateTime.UtcNow
        }, "tester");

        var persisted = await db.Members.AsNoTracking().SingleAsync();
        Assert.Equal("MB-00042-A", persisted.MemberNumber);

        var nextNumber = await db.SystemConfigEntries
            .AsNoTracking()
            .SingleAsync(e => e.Section == "Members" && e.Name == "MemberNumberNextNumber");
        Assert.Equal("43", nextNumber.Value);
    }

    [Fact]
    public async Task CreateAsync_AutoGeneratedMemberNumber_SkipsExistingNumbers()
    {
        using var connection = new SqliteConnection("Filename=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var db = new ApplicationDbContext(options);
        await db.Database.EnsureCreatedAsync();

        db.Members.Add(new Member
        {
            MemberNumber = "M-0001",
            FirstName = "Grace",
            LastName = "Hopper",
            IsActive = true,
            JoinedAt = DateTime.UtcNow
        });
        db.SystemConfigEntries.Add(new SystemConfigEntry
        {
            Section = "Members",
            Name = "MemberNumberNextNumber",
            Value = "1",
            Description = string.Empty,
            UpdatedAtUtc = DateTime.UtcNow
        });
        await db.SaveChangesAsync();

        var service = new MemberFeatureService(db, new NoopAuditLogService());

        await service.CreateAsync(new Member
        {
            FirstName = "Katherine",
            LastName = "Johnson",
            IsActive = true,
            JoinedAt = DateTime.UtcNow
        }, "tester");

        var generated = await db.Members
            .AsNoTracking()
            .Where(m => m.FirstName == "Katherine")
            .SingleAsync();

        Assert.Equal("M-0002", generated.MemberNumber);
    }

    [Fact]
    public async Task UpdateAsync_PersistsExtendedMemberFields()
    {
        using var connection = new SqliteConnection("Filename=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var db = new ApplicationDbContext(options);
        await db.Database.EnsureCreatedAsync();

        var membershipType = new MembershipType { Key = "Ehrenmitglied", Name = "Ehrenmitglied", IsActive = true };
        db.MembershipTypes.Add(membershipType);

        db.Members.Add(new Member
        {
            MemberNumber = "M-1000",
            FirstName = "Anna",
            LastName = "Beispiel",
            Email = "anna@example.org",
            IsActive = true,
            JoinedAt = DateTime.UtcNow.AddDays(-10),
            OauthID = "oauth-old",
            OAuthUserName = "anna.old",
            IsVerified = false,
            NotifyViaEmail = false,
            NotifyViaMatrix = false
        });
        await db.SaveChangesAsync();

        var existing = await db.Members.SingleAsync();
        var service = new MemberFeatureService(db, new NoopAuditLogService());

        var updatedMember = new Member
        {
            Id = existing.Id,
            MemberNumber = existing.MemberNumber,
            FirstName = existing.FirstName,
            LastName = existing.LastName,
            Email = existing.Email,
            IsActive = existing.IsActive,
            JoinedAt = existing.JoinedAt,
            OauthID = "oauth-new",
            OAuthUserName = "anna.new",
            IsVerified = true,
            Joined = DateTime.UtcNow.AddYears(-1),
            Leaved = DateTime.UtcNow,
            IsDeceased = true,
            MembershipTypeId = membershipType.Id,
            NotifyViaEmail = true,
            NotifyViaMatrix = true,
            DataprivacyAccepted = true,
            NewsletterConsent = true,
            ProfileImagePath = "/images/member.png",
            PendingEmail = "pending@example.org",
            EmailVerificationToken = "token-123",
            EmailVerificationTokenExpiry = DateTime.UtcNow.AddHours(2),
            RentalPayoutOptions = "[{\"method\":\"iban\"}]",
            InitPassword = "secret",
            KeycloakUsername = "anna.keycloak"
        };

        var result = await service.UpdateAsync(updatedMember, "tester");

        Assert.Equal(MemberMutationStatus.Success, result);

        var persisted = await db.Members.AsNoTracking().SingleAsync(m => m.Id == existing.Id);
        Assert.Equal("oauth-new", persisted.OauthID);
        Assert.Equal("anna.new", persisted.OAuthUserName);
        Assert.True(persisted.IsVerified);
        Assert.Equal(updatedMember.Joined, persisted.Joined);
        Assert.Equal(updatedMember.Leaved, persisted.Leaved);
        Assert.True(persisted.IsDeceased);
        Assert.Equal(membershipType.Id, persisted.MembershipTypeId);
        Assert.True(persisted.NotifyViaEmail);
        Assert.True(persisted.NotifyViaMatrix);
        Assert.True(persisted.DataprivacyAccepted);
        Assert.True(persisted.NewsletterConsent);
        Assert.Equal("/images/member.png", persisted.ProfileImagePath);
        Assert.Equal("pending@example.org", persisted.PendingEmail);
        Assert.Equal("token-123", persisted.EmailVerificationToken);
        Assert.NotNull(persisted.EmailVerificationTokenExpiry);
        Assert.Equal("[{\"method\":\"iban\"}]", persisted.RentalPayoutOptions);
        Assert.Equal("secret", persisted.InitPassword);
        Assert.Equal("anna.keycloak", persisted.KeycloakUsername);
        Assert.NotNull(persisted.LastUpdated);
    }

    [Fact]
    public async Task CreateAsync_WithMembershipTypeAndMetadata_PersistsMetadataValuesAndAuditsThem()
    {
        using var connection = new SqliteConnection("Filename=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var db = new ApplicationDbContext(options);
        await db.Database.EnsureCreatedAsync();

        var vereinType = new MembershipType { Key = "Verein", Name = "Verein", IsActive = true };
        db.MembershipTypes.Add(vereinType);
        await db.SaveChangesAsync();

        var clubNameField = new MembershipTypeField
        {
            MembershipTypeId = vereinType.Id,
            Key = "club_name",
            Label = "Vereinsname",
            FieldType = MemberMetadataFieldType.Text,
            IsRequired = true
        };
        db.MembershipTypeFields.Add(clubNameField);
        await db.SaveChangesAsync();

        var auditLogService = new CapturingAuditLogService();
        var service = new MemberFeatureService(db, auditLogService, new MemberMetadataService());

        var member = new Member
        {
            FirstName = "Verein",
            LastName = "Beispiel",
            IsActive = true,
            JoinedAt = DateTime.UtcNow,
            MembershipTypeId = vereinType.Id,
            MetadataInputs = new Dictionary<string, string?> { ["club_name"] = "Modellbauverein e.V." }
        };

        await service.CreateAsync(member, "tester");

        var persistedValue = await db.MemberMetadataValues.AsNoTracking().SingleAsync(v => v.MemberId == member.Id);
        Assert.Equal(clubNameField.Id, persistedValue.FieldId);
        Assert.Equal("Modellbauverein e.V.", persistedValue.Value);

        Assert.Equal("Members.Create", auditLogService.LastAction);
        Assert.Null(auditLogService.LastBefore);
        var afterSnapshot = Assert.IsType<Member>(auditLogService.LastAfter);
        Assert.NotNull(afterSnapshot.MembershipType);
        Assert.Equal("Verein", afterSnapshot.MembershipType!.Key);
        Assert.Single(afterSnapshot.MetadataValues);
        Assert.Equal("Modellbauverein e.V.", afterSnapshot.MetadataValues[0].Value);
    }

    [Fact]
    public async Task UpdateAsync_ChangingMembershipType_RemovesStaleMetadataAndPersistsNewValues()
    {
        using var connection = new SqliteConnection("Filename=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var db = new ApplicationDbContext(options);
        await db.Database.EnsureCreatedAsync();

        var vereinType = new MembershipType { Key = "Verein", Name = "Verein", IsActive = true };
        var firmaType = new MembershipType { Key = "Firma", Name = "Firma", IsActive = true };
        db.MembershipTypes.AddRange(vereinType, firmaType);
        await db.SaveChangesAsync();

        var clubNameField = new MembershipTypeField { MembershipTypeId = vereinType.Id, Key = "club_name", Label = "Vereinsname", FieldType = MemberMetadataFieldType.Text };
        var companyNameField = new MembershipTypeField { MembershipTypeId = firmaType.Id, Key = "company_name", Label = "Firmenname", FieldType = MemberMetadataFieldType.Text };
        db.MembershipTypeFields.AddRange(clubNameField, companyNameField);
        await db.SaveChangesAsync();

        var member = new Member
        {
            MemberNumber = "M-2000",
            FirstName = "Wechsel",
            LastName = "Beispiel",
            IsActive = true,
            JoinedAt = DateTime.UtcNow,
            MembershipTypeId = vereinType.Id
        };
        db.Members.Add(member);
        await db.SaveChangesAsync();

        db.MemberMetadataValues.Add(new MemberMetadataValue { MemberId = member.Id, FieldId = clubNameField.Id, Value = "Alter Verein e.V." });
        await db.SaveChangesAsync();

        var auditLogService = new CapturingAuditLogService();
        var service = new MemberFeatureService(db, auditLogService, new MemberMetadataService());

        var updatedMember = new Member
        {
            Id = member.Id,
            MemberNumber = member.MemberNumber,
            FirstName = member.FirstName,
            LastName = member.LastName,
            IsActive = member.IsActive,
            JoinedAt = member.JoinedAt,
            MembershipTypeId = firmaType.Id,
            MetadataInputs = new Dictionary<string, string?> { ["company_name"] = "Neue Firma GmbH" }
        };

        var result = await service.UpdateAsync(updatedMember, "tester");

        Assert.Equal(MemberMutationStatus.Success, result);

        var remainingValues = await db.MemberMetadataValues.AsNoTracking().Where(v => v.MemberId == member.Id).ToListAsync();
        Assert.Single(remainingValues);
        Assert.Equal(companyNameField.Id, remainingValues[0].FieldId);
        Assert.Equal("Neue Firma GmbH", remainingValues[0].Value);

        var afterSnapshot = Assert.IsType<Member>(auditLogService.LastAfter);
        Assert.Equal("Firma", afterSnapshot.MembershipType?.Key);
        Assert.Single(afterSnapshot.MetadataValues);

        var beforeSnapshot = Assert.IsType<Member>(auditLogService.LastBefore);
        Assert.Equal("Verein", beforeSnapshot.MembershipType?.Key);
        Assert.Single(beforeSnapshot.MetadataValues);
        Assert.Equal("Alter Verein e.V.", beforeSnapshot.MetadataValues[0].Value);
    }

    [Fact]
    public async Task CreateAsync_MissingRequiredMetadataField_ThrowsValidationException()
    {
        using var connection = new SqliteConnection("Filename=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var db = new ApplicationDbContext(options);
        await db.Database.EnsureCreatedAsync();

        var vereinType = new MembershipType { Key = "Verein", Name = "Verein", IsActive = true };
        db.MembershipTypes.Add(vereinType);
        await db.SaveChangesAsync();

        db.MembershipTypeFields.Add(new MembershipTypeField
        {
            MembershipTypeId = vereinType.Id,
            Key = "club_name",
            Label = "Vereinsname",
            FieldType = MemberMetadataFieldType.Text,
            IsRequired = true
        });
        await db.SaveChangesAsync();

        var service = new MemberFeatureService(db, new NoopAuditLogService(), new MemberMetadataService());

        var member = new Member
        {
            FirstName = "Ohne",
            LastName = "Vereinsname",
            IsActive = true,
            JoinedAt = DateTime.UtcNow,
            MembershipTypeId = vereinType.Id
        };

        await Assert.ThrowsAsync<ClubGear.Services.ValidationException>(() => service.CreateAsync(member, "tester"));
    }

    [Fact]
    public async Task UpdateAsync_MemberReferenceCreatingGrandchild_ThrowsValidationException()
    {
        using var connection = new SqliteConnection("Filename=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var db = new ApplicationDbContext(options);
        await db.Database.EnsureCreatedAsync();

        var firmaType = new MembershipType { Key = "Firma", Name = "Firma", IsActive = true, AllowsSubMembers = true, SubMemberLabel = "Mitarbeiter" };
        db.MembershipTypes.Add(firmaType);
        await db.SaveChangesAsync();

        var refField = new MembershipTypeField { MembershipTypeId = firmaType.Id, Key = "main_member", Label = "Hauptmitglied", FieldType = MemberMetadataFieldType.MemberReference };
        db.MembershipTypeFields.Add(refField);
        await db.SaveChangesAsync();

        var parent = new Member { MemberNumber = "P-1", FirstName = "Firma", LastName = "AG", IsActive = true, JoinedAt = DateTime.UtcNow, MembershipTypeId = firmaType.Id };
        var child = new Member { MemberNumber = "C-1", FirstName = "Kind", LastName = "Mueller", IsActive = true, JoinedAt = DateTime.UtcNow, MembershipTypeId = firmaType.Id };
        var outsider = new Member { MemberNumber = "X-1", FirstName = "Aussen", LastName = "Stehend", IsActive = true, JoinedAt = DateTime.UtcNow, MembershipTypeId = firmaType.Id };
        db.Members.AddRange(parent, child, outsider);
        await db.SaveChangesAsync();

        // child references parent => child is an existing sub-member, parent is an existing parent.
        db.MemberMetadataValues.Add(new MemberMetadataValue { MemberId = child.Id, FieldId = refField.Id, Value = parent.Id.ToString() });
        await db.SaveChangesAsync();

        var service = new MemberFeatureService(db, new NoopAuditLogService(), new MemberMetadataService());

        // outsider tries to reference the child, which is itself a sub-member => grandchild.
        var updated = new Member
        {
            Id = outsider.Id,
            MemberNumber = outsider.MemberNumber,
            FirstName = outsider.FirstName,
            LastName = outsider.LastName,
            IsActive = true,
            JoinedAt = outsider.JoinedAt,
            MembershipTypeId = firmaType.Id,
            MetadataInputs = new Dictionary<string, string?> { ["main_member"] = child.Id.ToString() }
        };

        var ex = await Assert.ThrowsAsync<ClubGear.Services.ValidationException>(() => service.UpdateAsync(updated, "tester"));
        Assert.Contains("das selbst ein Untermitglied ist", ex.Message);

        // The stored sub-member link for the child must be untouched.
        var childValue = await db.MemberMetadataValues.AsNoTracking().SingleAsync(v => v.MemberId == child.Id);
        Assert.Equal(parent.Id.ToString(), childValue.Value);
    }

    [Fact]
    public async Task UpdateAsync_ValidParentReference_Persists()
    {
        using var connection = new SqliteConnection("Filename=:memory:");
        await connection.OpenAsync();

        var options = new DbContextOptionsBuilder<ApplicationDbContext>()
            .UseSqlite(connection)
            .Options;

        await using var db = new ApplicationDbContext(options);
        await db.Database.EnsureCreatedAsync();

        var firmaType = new MembershipType { Key = "Firma", Name = "Firma", IsActive = true, AllowsSubMembers = true, SubMemberLabel = "Mitarbeiter" };
        db.MembershipTypes.Add(firmaType);
        await db.SaveChangesAsync();

        var refField = new MembershipTypeField { MembershipTypeId = firmaType.Id, Key = "main_member", Label = "Hauptmitglied", FieldType = MemberMetadataFieldType.MemberReference };
        db.MembershipTypeFields.Add(refField);
        await db.SaveChangesAsync();

        var parent = new Member { MemberNumber = "P-1", FirstName = "Firma", LastName = "AG", IsActive = true, JoinedAt = DateTime.UtcNow, MembershipTypeId = firmaType.Id };
        var child = new Member { MemberNumber = "C-1", FirstName = "Kind", LastName = "Mueller", IsActive = true, JoinedAt = DateTime.UtcNow, MembershipTypeId = firmaType.Id };
        var outsider = new Member { MemberNumber = "X-1", FirstName = "Aussen", LastName = "Stehend", IsActive = true, JoinedAt = DateTime.UtcNow, MembershipTypeId = firmaType.Id };
        db.Members.AddRange(parent, child, outsider);
        await db.SaveChangesAsync();

        db.MemberMetadataValues.Add(new MemberMetadataValue { MemberId = child.Id, FieldId = refField.Id, Value = parent.Id.ToString() });
        await db.SaveChangesAsync();

        var service = new MemberFeatureService(db, new NoopAuditLogService(), new MemberMetadataService());

        // outsider links to the top-level container parent => valid single-level link.
        var updated = new Member
        {
            Id = outsider.Id,
            MemberNumber = outsider.MemberNumber,
            FirstName = outsider.FirstName,
            LastName = outsider.LastName,
            IsActive = true,
            JoinedAt = outsider.JoinedAt,
            MembershipTypeId = firmaType.Id,
            MetadataInputs = new Dictionary<string, string?> { ["main_member"] = parent.Id.ToString() }
        };

        var result = await service.UpdateAsync(updated, "tester");

        Assert.Equal(MemberMutationStatus.Success, result);
        var persisted = await db.MemberMetadataValues.AsNoTracking().SingleAsync(v => v.MemberId == outsider.Id);
        Assert.Equal(parent.Id.ToString(), persisted.Value);
    }

    private sealed class NoopAuditLogService : IAuditLogService
    {
        public Task LogAsync(AuditLogRecord record, CancellationToken cancellationToken = default)
        {
            return Task.CompletedTask;
        }

        public Task LogChangeAsync(
            string action,
            object? before,
            object? after,
            string? actor = null,
            string? source = null,
            string? targetType = null,
            string? targetId = null,
            object? metadata = null,
            CancellationToken cancellationToken = default)
        {
            return Task.CompletedTask;
        }
    }

    private sealed class CapturingAuditLogService : IAuditLogService
    {
        public string? LastAction { get; private set; }
        public object? LastBefore { get; private set; }
        public object? LastAfter { get; private set; }

        public Task LogAsync(AuditLogRecord record, CancellationToken cancellationToken = default)
        {
            LastAction = record.Action;
            LastBefore = record.Before;
            LastAfter = record.After;
            return Task.CompletedTask;
        }

        public Task LogChangeAsync(
            string action,
            object? before,
            object? after,
            string? actor = null,
            string? source = null,
            string? targetType = null,
            string? targetId = null,
            object? metadata = null,
            CancellationToken cancellationToken = default)
        {
            LastAction = action;
            LastBefore = before;
            LastAfter = after;
            return Task.CompletedTask;
        }
    }
}
